// @tm8/execution — the spawn block's public surface.
export { SpawnService, type SpawnServiceOptions } from './SpawnService.js';
export {
  DEFAULT_AGENT_TOOL,
  DEFAULT_MODEL,
  DEFAULT_PERMISSION_MODE,
  ECHO_AGENT_CMD,
  agentToolForModel,
  buildAgentCommand,
  composeEnv,
  composeManifest,
  echoAgentPath,
  resolveLaunchConfig,
  resolveWorkdir,
  shellQuote,
  withAgentResume,
  type ComposeManifestInput,
  type ResolvedLaunchConfig,
} from './manifest.js';
export {
  DEFAULT_MAX_SKILLS,
  resolveSkills,
  type ManifestSkill,
  type ResolvedSkillRow,
  type SkillResolution,
  type SkillResolutionOptions,
} from './skills.js';
export {
  extractCodexRolloutIdentity,
  resolveCodexNativeSessionId,
  type CodexRolloutIdentity,
} from './native-session.js';
export { SpawnError } from './types.js';
export type {
  AgentMode,
  CreateWorkSessionInput,
  CreateWorkSessionResult,
  GraphAuth,
  GraphPort,
  LoadSpawnContextInput,
  ManifestSkillContext,
  PermissionMode,
  ProjectContext,
  ResolvedInteractionProfileContext,
  InteractionProfilePinContext,
  RecordCommandInput,
  ResumeRequest,
  ResumeWorkSessionResult,
  SessionLaunchPosture,
  SpawnContext,
  SpawnRequest,
  SpawnResult,
  TaskContext,
  TeamMemberContext,
  Tm8Manifest,
  TransitionInput,
  WorkdirMode,
  WorkSessionResumeInfo,
  WorkSessionStatus,
} from './types.js';
