// @tm8/execution — the spawn block's public surface.
// Credential redaction is exported so the server's header readers (resolveHeaders,
// jevText) redact with the SAME grammar as the manifest and the DB guard (086).
export {
  containsSecretToken,
  redactSecretTokens,
  REDACTION_MARKER,
  SECRET_TOKEN_SOURCE,
} from './secret-redaction.js';
export {
  SpawnService,
  type CredentialContainmentCause,
  type CredentialContainmentResult,
  type SessionLiveCause,
  type SessionLiveListener,
  type SpawnServiceOptions,
} from './SpawnService.js';
export {
  DEFAULT_AGENT_TOOL,
  DEFAULT_MODEL,
  DEFAULT_PERMISSION_MODE,
  ECHO_AGENT_CMD,
  CODEX_LOOPBACK_CONFIG_OVERRIDES,
  CODEX_LOOPBACK_HOSTS,
  agentToolForModel,
  buildAgentCommand,
  buildCodexArgs,
  codexLoopbackConfigArgs,
  composeEnv,
  composeManifest,
  asPermissionMode,
  memberLaunchPreferences,
  echoAgentPath,
  resolveLaunchConfig,
  resolveCommandNetworkPolicy,
  resolveWorkdir,
  shellQuote,
  withAgentResume,
  type ComposeManifestInput,
  type ResolvedLaunchConfig,
} from './manifest.js';
export {
  HARNESS_SURFACES,
  LANE_BUNDLED_SKILLS_OFF,
  MINIMAL_MCP_CONFIG,
  asHarnessSurface,
  asReadHints,
  claudePluginConfigDir,
  harnessSurfaceEnv,
  pluginSkillIds,
  readInstalledClaudePlugins,
  readHintHookPath,
  type HarnessSurface,
} from './harness-surface.js';
export {
  assertCodexNetworkFeatureList,
  assertCodexNetworkRuntimeVersion,
  MINIMUM_CODEX_LOOPBACK_PROXY_VERSION,
  preflightCodexNetworkPolicy,
  type CodexNetworkPreflight,
} from './codex-network-preflight.js';
export {
  resolveSkills,
  skillIdentityKey,
  splitTaskSkillCollisions,
  type ResolvedSkillRow,
  type SkillResolution,
} from './skills.js';
export {
  extractCodexRolloutIdentity,
  resolveCodexNativeSessionId,
  resolveCodexRollout,
  type CodexRollout,
  type CodexRolloutIdentity,
} from './native-session.js';
export {
  AGENT_CREDENTIAL_CONFIG_DIR_VAR,
  AGENT_CREDENTIAL_SUPPRESSED_ENV_KEYS,
  AGENT_TOOL_CREDENTIAL_PROVIDER,
  agentCredentialEnv,
  agentCredentialProviderFor,
  agentCredentialXdgConfigHome,
  type AgentCredentialHome,
  type AgentCredentialHomePort,
  type AgentCredentialProvider,
} from './agent-credentials.js';
export { SpawnError } from './types.js';
export {
  materializeSpaceApiKeyHome,
  scrubSpaceSessionSecrets,
  spaceSessionHomeDir,
  spaceSessionsRoot,
  sweepSpaceSessionSecrets,
} from './space-credential-session-home.js';
export {
  resolveSessionCredentials,
  type CredentialResolutionDeps,
  type CredentialResolutionInput,
  type ResolvedSessionCredentials,
} from './credential-resolution.js';
export {
  branchNameFor,
  provisionWorktree,
  type ProvisionedWorktree,
  type ProvisionWorktreeParams,
} from './worktree-provisioning.js';
export {
  reconcileNodeWorktrees,
  type ReconcileParams,
  type WorktreeQuarantine,
  type WorktreeReconcileReport,
  type WorktreeRepair,
} from './worktree-reconcile.js';
export type {
  AgentMode,
  CommandNetworkPolicy,
  CreateWorkSessionInput,
  CreateWorkSessionResult,
  GraphAuth,
  GraphPort,
  GitHubCredential,
  GitHubCredentialPort,
  SpaceCredentialGrant,
  SpaceCredentialPolicies,
  SpaceCredentialPort,
  SpaceCredentialProvider,
  SpaceCredentialRead,
  SpaceCredentialRefusalReason,
  SpaceCredentialRepoint,
  LoadSpawnContextInput,
  ContextDrop,
  ContextEntryRecord,
  ContextGroupAudit,
  ContextGroupName,
  ContextVia,
  LaunchHarnessRecord,
  ManifestContext,
  ManifestSkillContext,
  SpawnContextAudit,
  PermissionMode,
  ProjectContext,
  ResolvedInteractionProfileContext,
  InteractionProfilePinContext,
  RecordCommandInput,
  ResumeRequest,
  ResumeWorkSessionResult,
  SessionLaunchPosture,
  ShellSessionContext,
  ShellSessionRequest,
  ShellSessionResult,
  StartShellSessionResult,
  SpawnContext,
  SpawnRequest,
  SpawnResult,
  TaskContext,
  TeamMemberContext,
  Tm8Manifest,
  TransitionInput,
  WorkdirMode,
  WorkSessionResumeInfo,
  WorkSessionStatus,
  WorktreeAllocationRow,
  WorktreeAllocationState,
  GhostReconcileReport,
} from './types.js';

export { computeEffectiveSkills, type EffectiveSkillsInput } from './effective-skills.js';
