-- =============================================================================
-- 078 — Two write surfaces 057 and 006 deliberately left for the phase that is
-- now happening:
--
--   A. The worktree PROVISIONING and RECONCILIATION surface. 057 shipped
--      `worktrees` + `worktree_allocations` + the two semantic doors, and said
--      so in its own §8 comment: "Allocation writes belong to the provisioning
--      saga and reconciler, which arrive with their own (security definer)
--      surface in the spawn-integration phase; until then the table is
--      owner-writable only." This is that surface.
--
--   B. The tracking OBSERVER surface. 006 created
--      `public.tracking_refresh_requests` for "a worker with provider
--      credentials", and 017/034 shipped the enqueue door — but nothing has
--      ever drained the queue. This adds claim/complete and the two
--      fact-application doors the observer writes through.
--
-- Design oracle for A: docs/features/worktrees/WORKTREE-DESIGN.md
--   §3.2 allocation table · §4 provisioning saga · §5.1 lock ordering
--   §5.3 cleanup · §5.4 preflight · §6 startup reconciliation.
--
-- ⚠ LOCK ORDERING, restated because it is the one thing that deadlocks
-- (design §5.1, echoed at 057:238-242): every ledgered door takes
-- `internal.ledger_replay`'s advisory lock as its FIRST statement. The
-- per-project Git lock therefore lives OUTSIDE and BEFORE the ledgered
-- transaction, in the node's WorktreeManager. NOTHING in this file takes an
-- advisory lock, and the allocation doors below are deliberately UNLEDGERED —
-- allocation churn is operational truth, not a semantic command, and giving it
-- a client mutation id would invite it into the replay lock's blast radius for
-- no benefit.
--
-- ⚠ NO SNAPSHOT TRIGGER is added to `worktree_allocations` here, and none may
-- ever be: 057's §3 header makes "a write here is mechanically incapable of
-- bumping entities.version" a structural guarantee the memories lane depends
-- on (MEMO-WORKTREE-SEAM-ANSWERS.md W3).
-- =============================================================================

set role tm8_graph_owner;

-- -----------------------------------------------------------------------------
-- A1. The allocation row learns where its own directory is.
--
-- 057's table carries no project, path or branch: those live on
-- `public.worktrees`, which does not exist until saga step 6. That is fine for
-- the happy path and fatal for §6 reconciliation, whose whole job is the rows
-- where step 6 never happened — a `preparing` allocation with no entity cannot
-- name the directory the reconciler is supposed to remove.
--
-- Nullable, deliberately: 057's own proof driver (db/test/worktrees.mjs) inserts
-- allocation rows with three columns, and a NOT NULL here would break its 30
-- green assertions to buy nothing. The saga always populates them.
-- -----------------------------------------------------------------------------
alter table public.worktree_allocations
  add column if not exists project_id uuid,
  add column if not exists path       text,
  add column if not exists branch     text;

comment on column public.worktree_allocations.path is
  'Server-computed checkout path, denormalised from public.worktrees so a '
  'pre-entity (state=preparing) row can still be reconciled. Design §6.1.';

create index if not exists worktree_allocations_node_idx
  on public.worktree_allocations(node_id);

-- -----------------------------------------------------------------------------
-- A2. `create_worktree`, with the entity id supplied by the caller.
--
-- Design §4.4 requires the worktree id to be generated by the node BEFORE any
-- database write, because it is the allocation primary key and the allocation
-- is reserved (step 4) before the entity is created (step 6). 057's door minted
-- its own id through `internal.create_envelope`, which makes that ordering
-- impossible to honour: the saga would have to reserve under one id and create
-- under another, and the "deliberately no FK" note on the allocation table
-- would degrade from a design choice into an accident waiting to be noticed.
--
-- DROP then CREATE rather than `create or replace`: a trailing DEFAULT parameter
-- would make the old and new signatures ambiguous at the call site.
--
-- Everything else — the ledger label (`execution.spawn`, §2.7), the replay
-- binding shape, the space-projects admission check — is 057's, verbatim.
-- -----------------------------------------------------------------------------
drop function if exists public.create_worktree(uuid,uuid,text,text,text,text,uuid,text);

create function public.create_worktree(
  p_space_id uuid, p_project_id uuid, p_path text, p_branch text,
  p_base_ref text, p_base_commit_oid text, p_actor_id uuid default null,
  p_client_mutation_id text default null, p_entity_id uuid default null
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare
  replay jsonb;
  actor uuid;
  worktree_id uuid;
  activity_id uuid;
begin
  perform internal.require_replay_principal(p_client_mutation_id);
  replay := internal.ledger_replay(p_client_mutation_id, 'execution.spawn');
  if replay is not null then
    -- Security boundary: runs with ledger_replay's advisory lock HELD.
    perform internal.require_replay_principal(p_client_mutation_id);
    perform internal.require_replay_subject(
      replay #>> '{entity,space_id}', p_space_id::text, 'space');
    return replay;
  end if;
  perform internal.require_space_member(p_space_id);
  actor := internal.resolve_actor(p_actor_id, p_space_id);
  perform internal.bind_actor(actor);
  if not exists (select 1 from public.space_projects
                  where space_id = p_space_id and project_id = p_project_id) then
    raise exception 'project is not linked to this space' using errcode = '42501';
  end if;

  if p_entity_id is null then
    worktree_id := internal.create_envelope(p_space_id, 'worktree', actor, null, null);
  else
    -- The node-generated id, adopted verbatim. `create_envelope`'s insert,
    -- with `new_id()` replaced by the reservation's id and nothing else
    -- changed; the entities PK makes a collision a 23505, never a reuse.
    worktree_id := p_entity_id;
    insert into public.entities(id, space_id, kind, parent_id, position, created_by)
    values (worktree_id, p_space_id, 'worktree', null, null, actor);
  end if;

  insert into public.worktrees(entity_id, project_id, path, branch, base_ref, base_commit_oid)
  values (worktree_id, p_project_id, p_path, btrim(p_branch), p_base_ref, lower(p_base_commit_oid));
  perform internal.record_initial_version(worktree_id, actor);
  activity_id := internal.record_activity(p_space_id, worktree_id, actor, 'created',
                   null, jsonb_build_object('kind', 'worktree', 'branch', btrim(p_branch)));
  return internal.ledger_record(p_client_mutation_id, 'execution.spawn',
           internal.command_result(worktree_id, null, activity_id, array[worktree_id]));
end
$$;

-- -----------------------------------------------------------------------------
-- A3. Step 4 — reserve. Design §4.5.
--
-- Called by the node with the per-project Git lock ALREADY HELD and no ledger
-- in sight. The unique constraints on `public.worktrees` cannot help yet (that
-- row does not exist), so the allocation primary key is what turns a collision
-- into a 23505 instead of a silent reuse.
--
-- `p_cap` is the worktree cap of design §5.2 — separate from the session cap
-- because it bounds a different scarce resource (disk and .git/worktrees
-- metadata) and a worktree outlives the sessions that use it. 0 means no cap.
--
-- Counted over allocations that still HOLD DISK: preparing/ready/
-- cleanup_pending. `failed` holds nothing and is evidence only — and neither
-- does `missing`, which is precisely the state meaning "the directory is gone".
-- Counting `missing` would make every vanished checkout consume a cap slot
-- forever with no route back, since reconciliation treats `missing` as
-- terminal and nothing deletes allocation rows: a node with a cap set would
-- eventually refuse every spawn and need a manual SQL fix.
--
-- An exhausted `cleanup_pending` DOES still count, and should: that directory
-- is still on disk. Reconciliation reports it for an operator rather than
-- retrying forever.
-- -----------------------------------------------------------------------------
create or replace function public.reserve_worktree_allocation(
  p_worktree_entity_id uuid, p_space_id uuid, p_project_id uuid,
  p_node_id text, p_path text, p_branch text, p_cap integer default 0
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare live integer;
begin
  perform internal.require_space_member(p_space_id);
  if not exists (select 1 from public.space_projects
                  where space_id = p_space_id and project_id = p_project_id) then
    raise exception 'project is not linked to this space' using errcode = '42501';
  end if;
  if p_path is null or p_path not like '/%' or p_path like '%..%' then
    raise exception 'worktree path must be absolute and free of ..' using errcode = '22023';
  end if;

  if coalesce(p_cap, 0) > 0 then
    select count(*) into live from public.worktree_allocations
     where project_id = p_project_id
       and state in ('preparing','ready','cleanup_pending');
    if live >= p_cap then
      raise exception 'worktree cap reached for this project' using errcode = '53400',
        detail = 'worktree_cap';
    end if;
  end if;

  insert into public.worktree_allocations(
    worktree_entity_id, node_id, state, project_id, path, branch, attempts)
  values (p_worktree_entity_id, p_node_id, 'preparing', p_project_id, p_path, btrim(p_branch), 0);

  return jsonb_build_object('worktreeId', p_worktree_entity_id, 'state', 'preparing',
                            'path', p_path, 'branch', btrim(p_branch));
end
$$;

-- -----------------------------------------------------------------------------
-- A4. The operational state writer. Steps 5-8 and every §6.2 repair go through
--     here, so there is exactly one statement in the system that moves an
--     allocation between operational states.
--
-- It cannot touch `public.worktrees.status`: that is `update_worktree`'s alone
-- and 057's R29 guard makes an attempt a 23514 rather than a review comment.
-- The asymmetry is design §5.3's, deliberately — the entity records what was
-- DECIDED, the allocation records what has actually HAPPENED on disk.
-- -----------------------------------------------------------------------------
create or replace function public.set_worktree_allocation_state(
  p_worktree_entity_id uuid, p_state text,
  p_failure_code text default null, p_failure_detail jsonb default null,
  p_count_attempt boolean default false
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare alloc public.worktree_allocations;
begin
  perform internal.require_identity();
  if p_state not in ('preparing','ready','cleanup_pending','missing','failed') then
    raise exception 'invalid allocation state: %', p_state using errcode = '22023';
  end if;
  select * into alloc from public.worktree_allocations
   where worktree_entity_id = p_worktree_entity_id for update;
  if not found then
    raise exception 'no worktree allocation %', p_worktree_entity_id using errcode = 'P0002';
  end if;
  -- Once an entity exists the caller must be entitled to it. Before it exists
  -- there is nothing to be entitled to, and the reservation already checked
  -- membership; a bound identity is the honest gate for that window.
  if exists (select 1 from public.entities where id = p_worktree_entity_id) then
    perform internal.require_space_member(
      (select space_id from public.entities where id = p_worktree_entity_id));
  end if;

  update public.worktree_allocations
     set state = p_state,
         failure_code = case when p_state = 'failed' or p_state = 'cleanup_pending'
                             then coalesce(p_failure_code, failure_code) else null end,
         failure_detail = coalesce(p_failure_detail, failure_detail),
         attempts = attempts + (case when p_count_attempt then 1 else 0 end),
         last_reconciled_at = now()
   where worktree_entity_id = p_worktree_entity_id;

  return jsonb_build_object('worktreeId', p_worktree_entity_id, 'state', p_state);
end
$$;

-- -----------------------------------------------------------------------------
-- A5. The lease. Design §3.4 / §5.2: one write-capable live session per
--     worktree, enforced by 057's partial unique index — so contention is a
--     23505 here, which the node maps to `limit_exceeded`, never a queue and
--     never a hang.
--
-- ⚠ BOTH DOORS TAKE A SPACE CHECK, unconditionally.
--
-- A4's `require_identity()`-only gate is defensible only for the pre-entity
-- reservation window, where there is nothing yet to be entitled to. These two
-- doors have no such window: they operate on allocations whose entity exists
-- and whose lease is live. `release_worktree_lease` is the sharp one — the
-- single-writer invariant of §3.4 is enforced by a partial unique index over
-- `lease_session_id`, so clearing the lease is exactly what frees that index to
-- admit a SECOND session into the same working tree. Two agents writing one
-- checkout is real corruption, and "the worktree uuid is unguessable" is not an
-- authorization mechanism.
--
-- The space is one join away through `public.entities`; A1 denormalised
-- `project_id` onto the allocation, which makes it cheaper still.
-- -----------------------------------------------------------------------------
create or replace function internal.worktree_allocation_space(p_worktree_entity_id uuid)
returns uuid language sql stable set search_path = public, internal, pg_temp as $$
  select e.space_id from public.entities e where e.id = p_worktree_entity_id
$$;

create or replace function public.acquire_worktree_lease(
  p_worktree_entity_id uuid, p_session_id uuid
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare held uuid; alloc_space uuid;
begin
  perform internal.require_identity();
  select lease_session_id into held from public.worktree_allocations
   where worktree_entity_id = p_worktree_entity_id for update;
  if not found then
    raise exception 'no worktree allocation %', p_worktree_entity_id using errcode = 'P0002';
  end if;
  alloc_space := internal.worktree_allocation_space(p_worktree_entity_id);
  if alloc_space is null then
    -- Leasing something with no entity would be leasing a reservation, which
    -- no caller has a reason to do and the saga never does.
    raise exception 'worktree % has no entity to lease', p_worktree_entity_id using errcode = 'P0002';
  end if;
  perform internal.require_space_member(alloc_space);
  if held is not null and held <> p_session_id then
    raise exception 'worktree is already leased' using errcode = '53400', detail = 'worktree_leased';
  end if;
  update public.worktree_allocations
     set lease_session_id = p_session_id, lease_acquired_at = now()
   where worktree_entity_id = p_worktree_entity_id;
  return jsonb_build_object('worktreeId', p_worktree_entity_id, 'sessionId', p_session_id);
end
$$;

create or replace function public.release_worktree_lease(
  p_worktree_entity_id uuid
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare alloc_space uuid;
begin
  perform internal.require_identity();
  if not exists (select 1 from public.worktree_allocations
                  where worktree_entity_id = p_worktree_entity_id) then
    -- Reported rather than silently succeeding: a release that names nothing is
    -- a caller bug, and answering 'released: true' would hide it.
    raise exception 'no worktree allocation %', p_worktree_entity_id using errcode = 'P0002';
  end if;
  alloc_space := internal.worktree_allocation_space(p_worktree_entity_id);
  if alloc_space is not null then perform internal.require_space_member(alloc_space); end if;
  update public.worktree_allocations
     set lease_session_id = null, lease_acquired_at = null
   where worktree_entity_id = p_worktree_entity_id;
  return jsonb_build_object('worktreeId', p_worktree_entity_id, 'released', true);
end
$$;

-- -----------------------------------------------------------------------------
-- A6. Preflight token minting. Design §5.4 — the node runs the Git dirty and
--     unpushed probes (SQL cannot), digests the result, and writes it here;
--     `update_worktree` then refuses a delete whose token is absent, mismatched
--     or older than its 60-second TTL. This function is the write half of a
--     gate 057 already enforces.
--
-- ⚠ THIS DOOR HAS NO CALLER YET, AND THAT IS THE POINT OF THIS PARAGRAPH.
-- The node half of §5.4 — the `entities.patch` worktree arm that runs the Git
-- probes and mints the digest — is NOT in this change, so a `ready` worktree
-- cannot currently be deleted through `update_worktree` at all. That is a
-- deliberate scoping decision (see the PR), not an oversight.
--
-- What must NOT happen when someone wires it: this token is server-computed
-- from a real Git observation, or the gate it exists to close is defeated by
-- the caller it exists to constrain. A caller who can pass an arbitrary string
-- here and then present the same string to `update_worktree` has bypassed the
-- dirty/unpushed refusal entirely. The space check below bounds WHO can reach
-- the door; it does not and cannot make the token honest. Whoever lands the
-- patch arm owns that, and should read §5.4 before changing this function.
-- -----------------------------------------------------------------------------
create or replace function public.record_worktree_preflight(
  p_worktree_entity_id uuid, p_token text
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare alloc_space uuid;
begin
  perform internal.require_identity();
  if p_token is null or btrim(p_token) = '' then
    raise exception 'preflight token is required' using errcode = '22023';
  end if;
  alloc_space := internal.worktree_allocation_space(p_worktree_entity_id);
  if alloc_space is not null then perform internal.require_space_member(alloc_space); end if;
  update public.worktree_allocations
     set preflight_token = p_token, preflight_at = now()
   where worktree_entity_id = p_worktree_entity_id;
  if not found then
    raise exception 'no worktree allocation %', p_worktree_entity_id using errcode = 'P0002';
  end if;
  return jsonb_build_object('worktreeId', p_worktree_entity_id, 'preflightAt', now());
end
$$;

-- -----------------------------------------------------------------------------
-- A6b. The `in_worktree` edge, written UNDER THE WRITER TOKEN.
--
-- 052 added `in_worktree` to the origin-stamping branch and minted a
-- `worktree_manager` token for exactly this, with the stated purpose that "a
-- spawn-created association is distinguishable from a hand-drawn one". The
-- generic `public.write_edge` door sets no token, so an edge written through it
-- stamps `origin = 'user'` — which is the correct answer for a human drawing
-- the edge and the WRONG one for the provisioning saga. Going through
-- write_edge would have quietly made 052's token dead code and erased the one
-- distinction it exists to record.
--
-- Deliberately NOT recorder-owned: `in_worktree` stays an ordinarily mutable
-- association, correctable through generic edges.create/edges.delete (057:165).
-- This door changes who is recorded as having written it, not whether it can
-- ever be corrected.
-- -----------------------------------------------------------------------------
create or replace function public.link_session_worktree(
  p_session_id uuid, p_worktree_entity_id uuid
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare
  session_entity public.entities;
  edge_id uuid;
begin
  select * into session_entity from public.entities
   where id = p_session_id and deleted_at is null;
  if not found or session_entity.kind <> 'work_session' then
    raise exception 'no live work session %', p_session_id using errcode = 'P0002';
  end if;
  perform internal.require_space_member(session_entity.space_id);
  if not exists (select 1 from public.worktrees where entity_id = p_worktree_entity_id) then
    raise exception 'no worktree %', p_worktree_entity_id using errcode = 'P0002';
  end if;

  perform internal.w1_set_writer('worktree_manager');
  insert into public.edges(space_id, src_id, dst_id, type, created_by)
  values (session_entity.space_id, p_session_id, p_worktree_entity_id, 'in_worktree',
          internal.resolve_actor(null, session_entity.space_id))
  returning id into edge_id;
  perform internal.w1_set_writer('');

  return jsonb_build_object('edgeId', edge_id, 'sessionId', p_session_id,
                            'worktreeId', p_worktree_entity_id);
end
$$;

-- -----------------------------------------------------------------------------
-- A7. The reconciler's read. Design §6.1 cross-checks five sources; this
--     returns the two that live in Postgres (the allocation row and whether an
--     entity backs it), leaving Git, the filesystem and the live PTY map to the
--     node, which is the only place they can be observed.
--
-- `lease_session_status` is what turns §6.2's "lease held by a session with no
-- live PTY and a terminal status" from a guess into a fact.
-- -----------------------------------------------------------------------------
create or replace function public.node_worktree_allocations(p_node_id text)
returns table (
  worktree_entity_id uuid, project_id uuid, node_id text, state text,
  path text, branch text, lease_session_id uuid, attempts integer,
  failure_code text, entity_exists boolean, worktree_status text,
  lease_session_status text, updated_at timestamptz
) language sql security definer stable set search_path = public, internal, pg_temp as $$
  select a.worktree_entity_id, a.project_id, a.node_id, a.state,
         a.path, a.branch, a.lease_session_id, a.attempts, a.failure_code,
         (e.id is not null) as entity_exists,
         w.status as worktree_status,
         ls.status as lease_session_status,
         a.updated_at
    from public.worktree_allocations a
    left join public.entities e on e.id = a.worktree_entity_id and e.deleted_at is null
    left join public.worktrees w on w.entity_id = a.worktree_entity_id
    left join public.work_sessions ls on ls.entity_id = a.lease_session_id
   where a.node_id = p_node_id
   order by a.created_at;
$$;

-- -----------------------------------------------------------------------------
-- A8. Grants. 008's wholesale grant was a one-time statement; a function
--     created afterwards needs its own revoke/grant with the FULL argument
--     signature (050/053/057 precedent).
-- -----------------------------------------------------------------------------
revoke all on function public.create_worktree(uuid,uuid,text,text,text,text,uuid,text,uuid) from public;
grant execute on function public.create_worktree(uuid,uuid,text,text,text,text,uuid,text,uuid) to tm8_app;
revoke all on function public.reserve_worktree_allocation(uuid,uuid,uuid,text,text,text,integer) from public;
grant execute on function public.reserve_worktree_allocation(uuid,uuid,uuid,text,text,text,integer) to tm8_app;
revoke all on function public.set_worktree_allocation_state(uuid,text,text,jsonb,boolean) from public;
grant execute on function public.set_worktree_allocation_state(uuid,text,text,jsonb,boolean) to tm8_app;
revoke all on function public.acquire_worktree_lease(uuid,uuid) from public;
grant execute on function public.acquire_worktree_lease(uuid,uuid) to tm8_app;
revoke all on function public.release_worktree_lease(uuid) from public;
grant execute on function public.release_worktree_lease(uuid) to tm8_app;
revoke all on function public.record_worktree_preflight(uuid,text) from public;
grant execute on function public.record_worktree_preflight(uuid,text) to tm8_app;
revoke all on function public.node_worktree_allocations(text) from public;
grant execute on function public.node_worktree_allocations(text) to tm8_app;
revoke all on function public.link_session_worktree(uuid,uuid) from public;
grant execute on function public.link_session_worktree(uuid,uuid) to tm8_app;

-- =============================================================================
-- B. The tracking observer surface.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- B1. A claimed row needs to say WHEN it was claimed, or a node that dies
--     mid-fetch strands its rows in 'running' forever with nothing able to tell
--     that apart from a slow fetch.
-- -----------------------------------------------------------------------------
alter table public.tracking_refresh_requests
  add column if not exists started_at timestamptz,
  add column if not exists attempts   integer not null default 0;

-- -----------------------------------------------------------------------------
-- B2. `fetched_at` is an OBSERVATION, not content — and the difference matters
--     because 017:54 versions `pull_requests` on every UPDATE.
--
-- Without this, a poller doing its job (recording that it looked, and found
-- nothing new) would bump `entities.version` on every tick, and every staleness
-- signal in the system — the thing versioning exists for — would go off
-- permanently for every tracked PR. The observer would be a version-churn
-- machine wearing a freshness costume.
--
-- So: the snapshot triggers are narrowed to the columns that carry meaning. A
-- state change still versions. A refresh that changed nothing does not. This
-- replaces 017's triggers by name; the function they call is untouched.
--
-- (`internal.snapshot_entity_version` already short-circuits on
-- `to_jsonb(new) - 'updated_at' = to_jsonb(old) - 'updated_at'` at 001:1138 —
-- it subtracts `updated_at` but NOT `fetched_at`, which is exactly why that
-- guard does not save us here and this narrowing is load-bearing rather than
-- decorative.)
--
-- ⚠ INVARIANT, AND NOTHING BUT THIS COMMENT AND ONE TEST ENFORCES IT:
--
--   each WHEN list below must equal its table's CONTENT columns —
--   every column except entity_id, space_id, created_at, updated_at, fetched_at.
--
-- Add a column to `pull_requests` or `commits` and forget this file, and that
-- column never bumps `entities.version` again, for the life of the schema. No
-- migration errors, no test fails, and every staleness signal for that field is
-- silently dead. `db/test/worktree-provisioning.mjs` diffs these lists against
-- `information_schema.columns` for exactly that reason — if you are here
-- because that test went red, it is telling you to add your column to the WHEN
-- list, not to relax the test.
-- -----------------------------------------------------------------------------
drop trigger if exists pull_requests_w2_snapshot_version on public.pull_requests;
create trigger pull_requests_w2_snapshot_version after update on public.pull_requests
for each row when (
  new.provider is distinct from old.provider or new.url    is distinct from old.url
  or new.repo  is distinct from old.repo     or new.number is distinct from old.number
  or new.title is distinct from old.title    or new.state  is distinct from old.state
  or new.head_sha is distinct from old.head_sha
) execute function internal.snapshot_entity_version();

drop trigger if exists commits_w2_snapshot_version on public.commits;
create trigger commits_w2_snapshot_version after update on public.commits
for each row when (
  new.provider is distinct from old.provider or new.url    is distinct from old.url
  or new.repo  is distinct from old.repo     or new.sha    is distinct from old.sha
  or new.message is distinct from old.message or new.author is distinct from old.author
  or new.committed_at is distinct from old.committed_at
) execute function internal.snapshot_entity_version();

-- -----------------------------------------------------------------------------
-- B3. Claim. `for update skip locked` is what makes this safe to call from more
--     than one observer without a distributed lock: two claimers take disjoint
--     rows or one takes none, never the same row twice.
--
-- Stale 'running' rows are returned to the queue in the same statement, bounded
-- by `p_stale_after_seconds`. That is the only reason B1's `started_at` exists.
--
-- security definer, and READ-ONLY of nothing: 008 grants tm8_app select on this
-- table but no update, which is correct — the queue is not a client surface.
--
-- ⚠ THE CLAIM PREDICATE MUST MATCH THE APPLY DOORS' PREDICATE.
--
-- `apply_pull_request_facts` and `apply_commit_facts` call
-- `require_space_member(row.space_id)`, which has no node-admin bypass. If this
-- door claimed rows for spaces the caller is not in, every such row would be
-- claimed, fail 42501 on apply, and — being oldest by `created_at` — be
-- reclaimed and fail identically on every subsequent tick. One unreachable row
-- would wedge the whole queue permanently. So the claim is scoped to the
-- caller's memberships, and the two doors now agree about who may act.
--
-- `p_max_attempts` is the second half of that guarantee: a row that keeps
-- failing is retired rather than retried forever. The `attempts` column existed
-- and was incremented but read by nobody, which made it decoration.
-- -----------------------------------------------------------------------------
create or replace function public.claim_tracking_refresh(
  p_limit integer default 10, p_stale_after_seconds integer default 600,
  p_max_attempts integer default 5
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare claimed jsonb;
begin
  perform internal.require_identity();

  update public.tracking_refresh_requests
     set status = 'queued', started_at = null
   where status = 'running'
     and started_at is not null
     and started_at < now() - make_interval(secs => greatest(p_stale_after_seconds, 1));

  -- Retire the rows that have burned their budget. Recorded as `failed` with a
  -- reason rather than left queued, so an operator sees a terminal row instead
  -- of a tick that mysteriously never finishes.
  update public.tracking_refresh_requests
     set status = 'failed',
         error = coalesce(error, '') ||
                 case when coalesce(error, '') = '' then '' else '; ' end ||
                 'retired after ' || attempts || ' attempts',
         completed_at = now()
   where status = 'queued'
     and attempts >= greatest(coalesce(p_max_attempts, 5), 1);

  with picked as (
    select id from public.tracking_refresh_requests r
     where r.status = 'queued'
       -- Same entitlement the apply doors enforce. Claiming what we could never
       -- apply is what turns one bad row into a permanent wedge.
       and internal.is_space_member(r.space_id)
     order by r.created_at
     limit greatest(coalesce(p_limit, 10), 1)
     for update skip locked
  ), taken as (
    update public.tracking_refresh_requests r
       set status = 'running', started_at = now(), attempts = r.attempts + 1
      from picked
     where r.id = picked.id
     returning r.id, r.space_id, r.entity_ids, r.attempts
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'requestId', t.id, 'spaceId', t.space_id, 'attempts', t.attempts,
           'targets', coalesce((
             select jsonb_agg(jsonb_build_object(
                      'entityId', e.id, 'kind', e.kind,
                      'provider', coalesce(pr.provider, c.provider),
                      'repo',     coalesce(pr.repo, c.repo),
                      'number',   pr.number,
                      'sha',      c.sha))
               from public.entities e
               left join public.pull_requests pr on pr.entity_id = e.id
               left join public.commits c        on c.entity_id  = e.id
              where e.space_id = t.space_id
                and e.deleted_at is null
                and e.kind in ('pull_request','commit')
                -- An empty/absent entity_ids means "everything tracked in this
                -- space", which is what 017's door accepts and records.
                and (t.entity_ids is null or cardinality(t.entity_ids) = 0
                     or e.id = any(t.entity_ids))
           ), '[]'::jsonb))), '[]'::jsonb)
    into claimed
    from taken t;

  return jsonb_build_object('claimed', claimed);
end
$$;

-- `p_status` exists so PARTIAL SUCCESS CAN BE TOLD THE TRUTH.
--
-- Deriving the status from `p_error` alone forces a lie in the common case: a
-- request naming ten PRs where one 404s has persisted nine real facts, and
-- recording it as `failed` says the opposite. The observer decides — `failed`
-- only when nothing was learned — and `error` carries the per-target problems
-- eitherway, so a partial result is visible rather than averaged away.
-- (`006:165`'s CHECK has no `partial`, and widening a shipped constraint to
-- gain a fourth word is not worth it when `completed` + a populated `error`
-- already says it.)
create or replace function public.complete_tracking_refresh(
  p_request_id uuid, p_error text default null, p_status text default null
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare final_status text;
begin
  perform internal.require_identity();
  final_status := coalesce(p_status, case when p_error is null then 'completed' else 'failed' end);
  if final_status not in ('completed','failed') then
    raise exception 'invalid tracking refresh status: %', final_status using errcode = '22023';
  end if;
  update public.tracking_refresh_requests
     set status = final_status,
         error = p_error,
         completed_at = now()
   where id = p_request_id;
  if not found then
    raise exception 'no tracking refresh request %', p_request_id using errcode = 'P0002';
  end if;
  return jsonb_build_object('requestId', p_request_id, 'status', final_status);
end
$$;

-- -----------------------------------------------------------------------------
-- B4. Fact application. The observer holds provider credentials (S15 keeps them
--     out of Postgres) and hands back only what it read.
--
-- A NULL argument means "the provider did not tell me", and leaves the stored
-- value alone — the difference between an unknown and an erasure. `fetched_at`
-- is stamped either way, because "I looked and learned nothing" is itself a
-- fact worth recording, and B2 is what makes recording it free.
-- -----------------------------------------------------------------------------
create or replace function public.apply_pull_request_facts(
  p_entity_id uuid, p_title text default null, p_state text default null,
  p_head_sha text default null
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare row public.pull_requests;
begin
  perform internal.require_identity();
  select * into row from public.pull_requests where entity_id = p_entity_id for update;
  if not found then
    raise exception 'no pull request %', p_entity_id using errcode = 'P0002';
  end if;
  perform internal.require_space_member(row.space_id);
  if p_state is not null and p_state not in ('open','merged','closed','draft') then
    raise exception 'invalid pull request state: %', p_state using errcode = '22023';
  end if;

  update public.pull_requests
     set title      = coalesce(p_title, title),
         state      = coalesce(p_state, state),
         head_sha   = coalesce(p_head_sha, head_sha),
         fetched_at = now(),
         updated_at = now()
   where entity_id = p_entity_id;

  return jsonb_build_object('entityId', p_entity_id, 'state', coalesce(p_state, row.state),
                            'changed', (coalesce(p_title, row.title) is distinct from row.title
                                     or coalesce(p_state, row.state) is distinct from row.state
                                     or coalesce(p_head_sha, row.head_sha) is distinct from row.head_sha));
end
$$;

create or replace function public.apply_commit_facts(
  p_entity_id uuid, p_message text default null, p_author text default null,
  p_committed_at timestamptz default null, p_url text default null
) returns jsonb language plpgsql security definer set search_path = public, internal, pg_temp as $$
declare row public.commits;
begin
  perform internal.require_identity();
  select * into row from public.commits where entity_id = p_entity_id for update;
  if not found then
    raise exception 'no commit %', p_entity_id using errcode = 'P0002';
  end if;
  perform internal.require_space_member(row.space_id);

  update public.commits
     set message      = coalesce(p_message, message),
         author       = coalesce(p_author, author),
         committed_at = coalesce(p_committed_at, committed_at),
         url          = coalesce(p_url, url),
         fetched_at   = now(),
         updated_at   = now()
   where entity_id = p_entity_id;

  return jsonb_build_object('entityId', p_entity_id,
                            'changed', (coalesce(p_message, row.message) is distinct from row.message
                                     or coalesce(p_author, row.author) is distinct from row.author));
end
$$;

revoke all on function public.claim_tracking_refresh(integer,integer,integer) from public;
grant execute on function public.claim_tracking_refresh(integer,integer,integer) to tm8_app;
revoke all on function public.complete_tracking_refresh(uuid,text,text) from public;
grant execute on function public.complete_tracking_refresh(uuid,text,text) to tm8_app;
revoke all on function public.apply_pull_request_facts(uuid,text,text,text) from public;
grant execute on function public.apply_pull_request_facts(uuid,text,text,text) to tm8_app;
revoke all on function public.apply_commit_facts(uuid,text,text,timestamptz,text) from public;
grant execute on function public.apply_commit_facts(uuid,text,text,timestamptz,text) to tm8_app;

reset role;
